"""followers

Revision ID: 332e30220f3b
Revises: 9b9ff139ea7d
Create Date: 2018-12-03 21:33:12.629282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332e30220f3b'
down_revision = '9b9ff139ea7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
